name: Build and Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main # Adjust if your default branch is different

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Ensure this matches your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Deploy to GitHub Pages
        uses: bitovi/github-actions-angular-to-github-pages@v1.0.0
        with:
          path: dist/browser # Adjust to your project's output directory
